FROM node:20-alpine
RUN corepack enable && corepack prepare pnpm@9.15.0 --activate
WORKDIR /app

RUN apk add --no-cache netcat-openbsd

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

COPY . .

RUN chmod +x docker/entrypoint.sh docker/wait-for-it.sh && \
    sed -i 's/\r$//' docker/entrypoint.sh docker/wait-for-it.sh

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

ENTRYPOINT ["/app/docker/entrypoint.sh"]
CMD ["pnpm", "dev"]
